/**
 * Helper functions for working with extracted entity collections
 * 
 * These collections are generated by scripts/extract-entities.js
 * and provide AI-extracted structured data from blog posts.
 * 
 * Usage:
 * ```ts
 * import { getExtractedCompanies, getExtractedPeople } from '@/lib/extracted-entities';
 * 
 * const companies = await getExtractedCompanies();
 * const topCompany = companies[0]; // Most mentioned company
 * ```
 */

import { getCollection, type CollectionEntry } from 'astro:content';

// Type exports for convenience
export type ExtractedPostEntity = CollectionEntry<'extractedPostEntities'>;
export type ExtractedCompany = CollectionEntry<'extractedCompanies'>;
export type ExtractedPerson = CollectionEntry<'extractedPeople'>;
export type ExtractedTopic = CollectionEntry<'extractedTopics'>;

/**
 * Get all extracted post entities
 * Returns AI-extracted data for each blog post
 */
export async function getExtractedPostEntities(): Promise<ExtractedPostEntity[]> {
  return await getCollection('extractedPostEntities');
}

/**
 * Get extracted entities for a specific post by slug
 */
export async function getExtractedPostEntity(slug: string): Promise<ExtractedPostEntity | undefined> {
  const entities = await getExtractedPostEntities();
  return entities.find((entity) => entity.id === slug);
}

/**
 * Get all extracted companies
 * Sorted by number of mentions (most mentioned first)
 */
export async function getExtractedCompanies(): Promise<ExtractedCompany[]> {
  const companies = await getCollection('extractedCompanies');
  return companies.sort((a, b) => b.data.mentions - a.data.mentions);
}

/**
 * Get a specific company by name or ID
 */
export async function getExtractedCompany(nameOrId: string): Promise<ExtractedCompany | undefined> {
  const companies = await getCollection('extractedCompanies');
  const normalized = nameOrId.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return companies.find(
    (company) => company.id === normalized || company.data.name.toLowerCase() === nameOrId.toLowerCase()
  );
}

/**
 * Get all extracted people
 * Sorted by number of mentions (most mentioned first)
 */
export async function getExtractedPeople(): Promise<ExtractedPerson[]> {
  const people = await getCollection('extractedPeople');
  return people.sort((a, b) => b.data.mentions - a.data.mentions);
}

/**
 * Get a specific person by name or ID
 */
export async function getExtractedPerson(nameOrId: string): Promise<ExtractedPerson | undefined> {
  const people = await getCollection('extractedPeople');
  const normalized = nameOrId.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return people.find(
    (person) => person.id === normalized || person.data.name.toLowerCase() === nameOrId.toLowerCase()
  );
}

/**
 * Get all extracted topics
 * Sorted by number of mentions (most mentioned first)
 */
export async function getExtractedTopics(): Promise<ExtractedTopic[]> {
  const topics = await getCollection('extractedTopics');
  return topics.sort((a, b) => b.data.mentions - a.data.mentions);
}

/**
 * Get a specific topic by name or ID
 */
export async function getExtractedTopic(nameOrId: string): Promise<ExtractedTopic | undefined> {
  const topics = await getCollection('extractedTopics');
  const normalized = nameOrId.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return topics.find(
    (topic) => topic.id === normalized || topic.data.name.toLowerCase() === nameOrId.toLowerCase()
  );
}

/**
 * Get posts that mention a specific company
 */
export async function getPostsForCompany(companyNameOrId: string): Promise<string[]> {
  const company = await getExtractedCompany(companyNameOrId);
  return company?.data.posts || [];
}

/**
 * Get posts that mention a specific person
 */
export async function getPostsForPerson(personNameOrId: string): Promise<string[]> {
  const person = await getExtractedPerson(personNameOrId);
  return person?.data.posts || [];
}

/**
 * Get posts about a specific topic
 */
export async function getPostsForTopic(topicNameOrId: string): Promise<string[]> {
  const topic = await getExtractedTopic(topicNameOrId);
  return topic?.data.posts || [];
}

/**
 * Get all facts from all posts
 * Optionally filter by category
 */
export async function getAllFacts(category?: 'insight' | 'trend' | 'philosophy' | 'announcement' | 'milestone') {
  const entities = await getExtractedPostEntities();
  const facts = entities.flatMap((entity) =>
    entity.data.facts.map((fact) => ({
      ...fact,
      postSlug: entity.id,
      postTitle: entity.data.title,
    }))
  );

  if (category) {
    return facts.filter((fact) => fact.category === category);
  }

  return facts;
}

/**
 * Get all figures from all posts
 * Useful for creating statistics pages
 */
export async function getAllFigures() {
  const entities = await getExtractedPostEntities();
  return entities.flatMap((entity) =>
    entity.data.figures.map((figure) => ({
      ...figure,
      postSlug: entity.id,
      postTitle: entity.data.title,
    }))
  );
}

/**
 * Search entities by keyword
 */
export async function searchEntities(keyword: string) {
  const [companies, people, topics] = await Promise.all([
    getExtractedCompanies(),
    getExtractedPeople(),
    getExtractedTopics(),
  ]);

  const lowerKeyword = keyword.toLowerCase();

  return {
    companies: companies.filter((c) => c.data.name.toLowerCase().includes(lowerKeyword)),
    people: people.filter((p) => p.data.name.toLowerCase().includes(lowerKeyword)),
    topics: topics.filter((t) => t.data.name.toLowerCase().includes(lowerKeyword)),
  };
}
